name: Generate Daily Sudoku Boards

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at 12 AM UTC

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Sudoku Generator
      run: docker build -t sudoku_generator:latest ./sudoku_generator

    - name: Run Dockerfile Logic
      run: docker run --rm -e POCKETBASE_ADMIN=${{ secrets.POCKETBASE_ADMIN }} -e POCKETBASE_PASSWORD=${{ secrets.POCKETBASE_PASSWORD }} sudoku_generator:latest